(define (subsets s)
  (if (null? s)
      (list '())
      (let ((rest (subsets (cdr s))))
        (append rest (map (lambda (rest)
                            (append (list (car s)) rest))
                            rest)))))
