(define (make-account balance secret-password)
  (let ((max 7)
        (times 0))
    (define (call-the-cops)
      (newline)
      (display "Too much times"))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (display-wrong-password-message useless-arg)             
      (begin (set! times (+ times 1))
             (if (>= times max)
                 (begin (display "Incorrect password") (call-the-cops))
                 (display "Incorrect password"))))
   
    (define (dispatch m1 m2)
      (if (eq? m1 secret-password)
          (cond ((eq? m2 'withdraw) withdraw)
                ((eq? m2 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACCOUNT"
                             m2)))
          display-wrong-password-message))
    dispatch))

(define acc (make-account 100 'secret-password))
